// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQIg-LKtkCeV4FX_eKeKArEqaPJTTKbB8',
    appId: '1:729455727817:web:3b2f37944ea5182391a918',
    messagingSenderId: '729455727817',
    projectId: 'electrohome-ecuador',
    authDomain: 'electrohome-ecuador.firebaseapp.com',
    storageBucket: 'electrohome-ecuador.firebasestorage.app',
    measurementId: 'G-932Z3RN44G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApdBCX4AA4DtMXL21DMqKyR-ci8oNwlqM',
    appId: '1:729455727817:android:af954357dff98f3f91a918',
    messagingSenderId: '729455727817',
    projectId: 'electrohome-ecuador',
    storageBucket: 'electrohome-ecuador.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKky5P1Je7i5d_qg7SKyyCnE0iquJEF20',
    appId: '1:729455727817:ios:897fb266d0e5401091a918',
    messagingSenderId: '729455727817',
    projectId: 'electrohome-ecuador',
    storageBucket: 'electrohome-ecuador.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKky5P1Je7i5d_qg7SKyyCnE0iquJEF20',
    appId: '1:729455727817:ios:897fb266d0e5401091a918',
    messagingSenderId: '729455727817',
    projectId: 'electrohome-ecuador',
    storageBucket: 'electrohome-ecuador.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQIg-LKtkCeV4FX_eKeKArEqaPJTTKbB8',
    appId: '1:729455727817:web:426d30385ae4843691a918',
    messagingSenderId: '729455727817',
    projectId: 'electrohome-ecuador',
    authDomain: 'electrohome-ecuador.firebaseapp.com',
    storageBucket: 'electrohome-ecuador.firebasestorage.app',
    measurementId: 'G-S5B59BJ2LE',
  );
}
